apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=shetty
resources:
  - efsprovisioner.yml
  - rbac.yml
  - create-storage.yml
  - deploy-mysql.yaml
  - deploy-wordpress.yaml