apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udcluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 3
     instanceType: t2.micro
     ssh:
        publicKeyName: iamkey
   
